default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: communicable_development
  pool: 5
  username: postgres
  password: Nairobi11
  host: localhost
  port: 5432

test:
  <<: *default
  database: communicable_test

production:
  <<: *default
  database: communicare_production
  username: communicare
  password: <%= ENV["COMMUNICARE_DATABASE_PASSWORD"] %>