source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.4"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.4.3'


# Use sqlite3 as the database for Active Record
gem 'pg'


gem 'railties'

gem 'active_model_serializers'
gem 'rack-cors'


# QR code generation
gem 'rqrcode'
gem 'importmap-rails'

# QR code scanning
# gem 'qrscanner', '~> 0.4.1'
# gem 'zxing'

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"
gem "bcrypt"
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

group :development, :test do
  # Original debug gem you have
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  
  # Additional recommended gems
  gem 'rspec-rails'          # Testing framework
  gem 'faker'                # Generates fake data for testing
  gem 'pry'                  # Better debugging
  gem 'pry-rails'           # Rails integration for pry
  gem 'byebug'              # Alternative debugger
  gem 'factory_bot_rails'   # Fixture replacement
end

group :development do
  gem 'better_errors'       # Better error pages
  gem 'binding_of_caller'   # Provides more REPL features
  gem 'annotate'           # Adds schema info to model files
  gem 'rails-erd'          # Generates entity relationship diagrams
end


gem 'stimulus-rails'
gem 'turbo-rails'
gem 'open-uri'
gem 'kaminari'
gem 'devise'
gem 'devise-jwt'
gem 'rack-attack'
